seed:
  123456
lr:
  0.0005
num_epochs:
  300
sample_interval:
  1000
save_model_interval:
  500
batch_size:
  1024
num_thetas:
  7
pos_dim:
  2
latent_dim:
  3
pos_test:
  [
    1.51,
   0.199
  ]
data_path:
  "data/inverse_data_7_1000_100.pickle"