seed:
  123456
lr:
  0.001.2
weight_pos:
  3
num_epochs:
  500
sample_interval:
  10
save_model_interval:
  200
batch_size:
  1024
num_thetas:
  7
pos_dim:
  2
latent_dim:
  3
pos_test:
  [
    3.51,
   0.00
  ]
data_path:
  "data/inverse_data_7_1000_100.pickle"
robot_arm:
  lengths:
    [0.5, 0.5, 1, 1, 1, 1]
  sigmas:
    [0.25, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]